version: '3'

services:
  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./postdatabase:/var/lib/postgresql/data

  backend:
    build:
      context: ~/devopswithdocker/material-applications
      dockerfile: ~/devopswithdocker/material-applications/example-backend/Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - db

  frontend:
    build:
      context: ~/devopswithdocker/material-applications
      dockerfile: ~/devopswithdocker/material-applications/example-frontend/Dockerfile
    ports:
      - 5000:5000
