version: '3'

services:
  backend:
    build:
      context: ~/devopswithdocker/material-applications
      dockerfile: ~/devopswithdocker/material-applications/example-backend/Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: ~/devopswithdocker/material-applications
      dockerfile: ~/devopswithdocker/material-applications/example-frontend/Dockerfile
    ports:
      - 5000:5000
